name: Build RSS (Hedgepoint HUB)

on:
  schedule:
    - cron: "*/30 * * * *"   # a cada 30 minutos
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build feed.xml
        env:
          BING_API_KEY: ${{ secrets.BING_API_KEY }}  # opcional
        run: |
          python feed_builder.py

      - name: Commit feed
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add feed.xml
            git commit -m "Update feed.xml"
            git push
          else
            echo "Nothing to commit"
          fi
      
      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: feed
          path: feed.xml
