name: Build RSS (Hedgepoint HUB)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build feed.xml
        env:
          BING_API_KEY: ${{ secrets.BING_API_KEY }}  # opcional
        run: |
          python feed_builder.py
          test -f feed.xml && ls -lh feed.xml

      - name: Commit & push feed.xml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update feed.xml" || echo "Nada para commitar"
          git push
